### PR TITLE
Made Python3 compatible

### PR DESCRIPTION
**Pull request by rgerkin**
All of this was done with 2to3 so I don't know if it broke anything.  Do you have any tests for it?

### CODE REVIEW

**Comment by cyrus-** [comment]
Looks mostly fine, though there are some inefficiencies introduced where it does like list(dict.keys) instead of just dict.keys because of how they changed the API with respect to iterables. If you want to, you could go in and fix those manually.

**Comment by rgerkin** [comment]
What's the alternative to list(dict.keys()) in Python3, to preserve efficiency?  If there is none, I can replace with try/except so only people running in Python3 take the performance hit.

**Comment by cyrus-** [comment]
dict.iterkeys() should be more efficient I think

**Comment by rgerkin** [comment]
dict.iterkeys() is not in Python 3.  dict.keys() is an iterator in Python 3, whereas in Python 2 it was a list, so presumably what is lost from converting it to a list is happening in Python 2 anyway.

**Comment by cyrus-** [comment]
Well, it should actually be an iterator in the code where it was changed I
think. So maybe for efficiency just change it to keys() instead of
list(keys()) everywhere?

Also, if you find out something doesn't work in Python 2.7 anymore, the
Python library 'six' usually has workarounds.

**Comment by rgerkin** [comment]
I don't think there are any .keys() calls there.  Do you mean .items()?  There are a lot of those wrapped in list(), most unnecessarily, but I'm actually not sure which of those are intended to be iterators downstream, and which are fine as lists.  If it's important to you, could you pick out the ones that you intended to be iterators, and then I'll fix those.

**Pull request merged**
